//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "value" })
@XmlRootElement(name = "bitmap")
public class Bitmap
{

	@XmlAttribute(name = "id", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String id;
	@XmlAttribute(name = "width", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String width;
	@XmlAttribute(name = "height", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String height;
	@XmlAttribute(name = "ColorSpace")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String colorSpace;
	@XmlAttribute(name = "BitsPerComponent")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String bitsPerComponent;
	@XmlAttribute(name = "ColorKey")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String colorKey;
	@XmlAttribute(name = "length")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String length;
	@XmlAttribute(name = "encoding")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String encoding;
	@XmlAttribute(name = "Filter")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String filter;
	@XmlValue
	protected String value;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWidth(String value)
	{
		this.width = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeight(String value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the colorSpace property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColorSpace()
	{
		if (colorSpace == null) {
			return "DeviceRGB";
		} else {
			return colorSpace;
		}
	}

	/**
	 * Sets the value of the colorSpace property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColorSpace(String value)
	{
		this.colorSpace = value;
	}

	/**
	 * Gets the value of the bitsPerComponent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBitsPerComponent()
	{
		if (bitsPerComponent == null) {
			return "8";
		} else {
			return bitsPerComponent;
		}
	}

	/**
	 * Sets the value of the bitsPerComponent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBitsPerComponent(String value)
	{
		this.bitsPerComponent = value;
	}

	/**
	 * Gets the value of the colorKey property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColorKey()
	{
		return colorKey;
	}

	/**
	 * Sets the value of the colorKey property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColorKey(String value)
	{
		this.colorKey = value;
	}

	/**
	 * Gets the value of the length property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLength()
	{
		return length;
	}

	/**
	 * Sets the value of the length property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLength(String value)
	{
		this.length = value;
	}

	/**
	 * Gets the value of the encoding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEncoding()
	{
		return encoding;
	}

	/**
	 * Sets the value of the encoding property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEncoding(String value)
	{
		this.encoding = value;
	}

	/**
	 * Gets the value of the filter property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFilter()
	{
		return filter;
	}

	/**
	 * Sets the value of the filter property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFilter(String value)
	{
		this.filter = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getvalue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setvalue(String value)
	{
		this.value = value;
	}

}
