//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "effect")
public class Effect
{

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "duration")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String duration;
	@XmlAttribute(name = "transition")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String transition;
	@XmlAttribute(name = "effect", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String effect;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the duration property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDuration()
	{
		return duration;
	}

	/**
	 * Sets the value of the duration property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDuration(String value)
	{
		this.duration = value;
	}

	/**
	 * Gets the value of the transition property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransition()
	{
		return transition;
	}

	/**
	 * Sets the value of the transition property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransition(String value)
	{
		this.transition = value;
	}

	/**
	 * Gets the value of the effect property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEffect()
	{
		return effect;
	}

	/**
	 * Sets the value of the effect property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEffect(String value)
	{
		this.effect = value;
	}

}
