//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "stop" })
@XmlRootElement(name = "gradient")
public class Gradient
{

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "type")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String type;
	@XmlAttribute(name = "extend")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String extend;
	@XmlAttribute(name = "matrix")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String matrix;
	@XmlAttribute(name = "coords", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String coords;
	@XmlElement(required = true)
	protected List<Stop> stop;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType()
	{
		if (type == null) {
			return "axial";
		} else {
			return type;
		}
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value)
	{
		this.type = value;
	}

	/**
	 * Gets the value of the extend property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExtend()
	{
		if (extend == null) {
			return "no";
		} else {
			return extend;
		}
	}

	/**
	 * Sets the value of the extend property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExtend(String value)
	{
		this.extend = value;
	}

	/**
	 * Gets the value of the matrix property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMatrix()
	{
		if (matrix == null) {
			return "1 0 0 1 0 0";
		} else {
			return matrix;
		}
	}

	/**
	 * Sets the value of the matrix property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMatrix(String value)
	{
		this.matrix = value;
	}

	/**
	 * Gets the value of the coords property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCoords()
	{
		return coords;
	}

	/**
	 * Sets the value of the coords property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCoords(String value)
	{
		this.coords = value;
	}

	/**
	 * Gets the value of the stop property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the stop property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getStop().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Stop }
	 * 
	 * 
	 */
	public List<Stop> getStop()
	{
		if (stop == null) {
			stop = new ArrayList<Stop>();
		}
		return this.stop;
	}

}
