//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "groupOrImageOrUseOrTextOrPath" })
@XmlRootElement(name = "group")
public class Group
{

	@XmlAttribute(name = "layer")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String layer;
	@XmlAttribute(name = "matrix")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String matrix;
	@XmlAttribute(name = "pin")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String pin;
	@XmlAttribute(name = "transformations")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String transformations;
	@XmlAttribute(name = "clip")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String clip;
	@XmlAttribute(name = "url")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String url;
	@XmlAttribute(name = "decoration")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String decoration;
	@XmlElements({ @XmlElement(name = "group", type = Group.class),
			@XmlElement(name = "image", type = Image.class),
			@XmlElement(name = "use", type = Use.class),
			@XmlElement(name = "text", type = Text.class),
			@XmlElement(name = "path", type = Path.class) })
	protected List<Object> groupOrImageOrUseOrTextOrPath;

	/**
	 * Gets the value of the layer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLayer()
	{
		return layer;
	}

	/**
	 * Sets the value of the layer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLayer(String value)
	{
		this.layer = value;
	}

	/**
	 * Gets the value of the matrix property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMatrix()
	{
		if (matrix == null) {
			return "1 0 0 1 0 0";
		} else {
			return matrix;
		}
	}

	/**
	 * Sets the value of the matrix property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMatrix(String value)
	{
		this.matrix = value;
	}

	/**
	 * Gets the value of the pin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPin()
	{
		return pin;
	}

	/**
	 * Sets the value of the pin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPin(String value)
	{
		this.pin = value;
	}

	/**
	 * Gets the value of the transformations property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransformations()
	{
		if (transformations == null) {
			return "affine";
		} else {
			return transformations;
		}
	}

	/**
	 * Sets the value of the transformations property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransformations(String value)
	{
		this.transformations = value;
	}

	/**
	 * Gets the value of the clip property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClip()
	{
		return clip;
	}

	/**
	 * Sets the value of the clip property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClip(String value)
	{
		this.clip = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl()
	{
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value)
	{
		this.url = value;
	}

	/**
	 * Gets the value of the decoration property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDecoration()
	{
		return decoration;
	}

	/**
	 * Sets the value of the decoration property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDecoration(String value)
	{
		this.decoration = value;
	}

	/**
	 * Gets the value of the groupOrImageOrUseOrTextOrPath property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the groupOrImageOrUseOrTextOrPath property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getGroupOrImageOrUseOrTextOrPath().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Group }
	 * {@link Image } {@link Use } {@link Text } {@link Path }
	 * 
	 * 
	 */
	public List<Object> getGroupOrImageOrUseOrTextOrPath()
	{
		if (groupOrImageOrUseOrTextOrPath == null) {
			groupOrImageOrUseOrTextOrPath = new ArrayList<Object>();
		}
		return this.groupOrImageOrUseOrTextOrPath;
	}

}
