//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "info")
public class Info
{

	@XmlAttribute(name = "created")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String created;
	@XmlAttribute(name = "modified")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String modified;
	@XmlAttribute(name = "title")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String title;
	@XmlAttribute(name = "author")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String author;
	@XmlAttribute(name = "subject")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String subject;
	@XmlAttribute(name = "keywords")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String keywords;
	@XmlAttribute(name = "pagemode")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pagemode;
	@XmlAttribute(name = "numberpages")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String numberpages;

	/**
	 * Gets the value of the created property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCreated()
	{
		return created;
	}

	/**
	 * Sets the value of the created property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCreated(String value)
	{
		this.created = value;
	}

	/**
	 * Gets the value of the modified property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModified()
	{
		return modified;
	}

	/**
	 * Sets the value of the modified property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModified(String value)
	{
		this.modified = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle()
	{
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value)
	{
		this.title = value;
	}

	/**
	 * Gets the value of the author property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAuthor()
	{
		return author;
	}

	/**
	 * Sets the value of the author property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAuthor(String value)
	{
		this.author = value;
	}

	/**
	 * Gets the value of the subject property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubject()
	{
		return subject;
	}

	/**
	 * Sets the value of the subject property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubject(String value)
	{
		this.subject = value;
	}

	/**
	 * Gets the value of the keywords property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getKeywords()
	{
		return keywords;
	}

	/**
	 * Sets the value of the keywords property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setKeywords(String value)
	{
		this.keywords = value;
	}

	/**
	 * Gets the value of the pagemode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPagemode()
	{
		if (pagemode == null) {
			return "fullscreen";
		} else {
			return pagemode;
		}
	}

	/**
	 * Sets the value of the pagemode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPagemode(String value)
	{
		this.pagemode = value;
	}

	/**
	 * Gets the value of the numberpages property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumberpages()
	{
		return numberpages;
	}

	/**
	 * Sets the value of the numberpages property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumberpages(String value)
	{
		this.numberpages = value;
	}

}
