//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "info", "preamble", "bitmapOrIpestyle",
		"page" })
@XmlRootElement(name = "ipe")
public class Ipe
{

	@XmlAttribute(name = "creator")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String creator;
	@XmlAttribute(name = "version", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String version;
	protected Info info;
	protected Preamble preamble;
	@XmlElements({ @XmlElement(name = "bitmap", type = Bitmap.class),
			@XmlElement(name = "ipestyle", type = Ipestyle.class) })
	protected List<Object> bitmapOrIpestyle;
	@XmlElement(required = true)
	protected List<Page> page;

	/**
	 * Gets the value of the creator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCreator()
	{
		return creator;
	}

	/**
	 * Sets the value of the creator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCreator(String value)
	{
		this.creator = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion()
	{
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(String value)
	{
		this.version = value;
	}

	/**
	 * Gets the value of the info property.
	 * 
	 * @return possible object is {@link Info }
	 * 
	 */
	public Info getInfo()
	{
		return info;
	}

	/**
	 * Sets the value of the info property.
	 * 
	 * @param value
	 *            allowed object is {@link Info }
	 * 
	 */
	public void setInfo(Info value)
	{
		this.info = value;
	}

	/**
	 * Gets the value of the preamble property.
	 * 
	 * @return possible object is {@link Preamble }
	 * 
	 */
	public Preamble getPreamble()
	{
		return preamble;
	}

	/**
	 * Sets the value of the preamble property.
	 * 
	 * @param value
	 *            allowed object is {@link Preamble }
	 * 
	 */
	public void setPreamble(Preamble value)
	{
		this.preamble = value;
	}

	/**
	 * Gets the value of the bitmapOrIpestyle property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the bitmapOrIpestyle property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBitmapOrIpestyle().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Bitmap }
	 * {@link Ipestyle }
	 * 
	 * 
	 */
	public List<Object> getBitmapOrIpestyle()
	{
		if (bitmapOrIpestyle == null) {
			bitmapOrIpestyle = new ArrayList<Object>();
		}
		return this.bitmapOrIpestyle;
	}

	/**
	 * Gets the value of the page property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the page property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPage().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Page }
	 * 
	 * 
	 */
	public List<Page> getPage()
	{
		if (page == null) {
			page = new ArrayList<Page>();
		}
		return this.page;
	}

}
