//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "layout")
public class Layout
{

	@XmlAttribute(name = "paper", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String paper;
	@XmlAttribute(name = "origin", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String origin;
	@XmlAttribute(name = "frame", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String frame;
	@XmlAttribute(name = "crop")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String crop;
	@XmlAttribute(name = "skip")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String skip;

	/**
	 * Gets the value of the paper property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaper()
	{
		return paper;
	}

	/**
	 * Sets the value of the paper property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaper(String value)
	{
		this.paper = value;
	}

	/**
	 * Gets the value of the origin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrigin()
	{
		return origin;
	}

	/**
	 * Sets the value of the origin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOrigin(String value)
	{
		this.origin = value;
	}

	/**
	 * Gets the value of the frame property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFrame()
	{
		return frame;
	}

	/**
	 * Sets the value of the frame property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFrame(String value)
	{
		this.frame = value;
	}

	/**
	 * Gets the value of the crop property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCrop()
	{
		if (crop == null) {
			return "yes";
		} else {
			return crop;
		}
	}

	/**
	 * Sets the value of the crop property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCrop(String value)
	{
		this.crop = value;
	}

	/**
	 * Gets the value of the skip property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSkip()
	{
		return skip;
	}

	/**
	 * Sets the value of the skip property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSkip(String value)
	{
		this.skip = value;
	}

}
