//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the de.topobyte.ipe.jaxb.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: de.topobyte.ipe.jaxb.model
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link Preamble }
	 * 
	 */
	public Preamble createPreamble()
	{
		return new Preamble();
	}

	/**
	 * Create an instance of {@link Symbol }
	 * 
	 */
	public Symbol createSymbol()
	{
		return new Symbol();
	}

	/**
	 * Create an instance of {@link Group }
	 * 
	 */
	public Group createGroup()
	{
		return new Group();
	}

	/**
	 * Create an instance of {@link Image }
	 * 
	 */
	public Image createImage()
	{
		return new Image();
	}

	/**
	 * Create an instance of {@link Use }
	 * 
	 */
	public Use createUse()
	{
		return new Use();
	}

	/**
	 * Create an instance of {@link Text }
	 * 
	 */
	public Text createText()
	{
		return new Text();
	}

	/**
	 * Create an instance of {@link Path }
	 * 
	 */
	public Path createPath()
	{
		return new Path();
	}

	/**
	 * Create an instance of {@link Color }
	 * 
	 */
	public Color createColor()
	{
		return new Color();
	}

	/**
	 * Create an instance of {@link Gridsize }
	 * 
	 */
	public Gridsize createGridsize()
	{
		return new Gridsize();
	}

	/**
	 * Create an instance of {@link Tiling }
	 * 
	 */
	public Tiling createTiling()
	{
		return new Tiling();
	}

	/**
	 * Create an instance of {@link Layer }
	 * 
	 */
	public Layer createLayer()
	{
		return new Layer();
	}

	/**
	 * Create an instance of {@link View }
	 * 
	 */
	public View createView()
	{
		return new View();
	}

	/**
	 * Create an instance of {@link Textsize }
	 * 
	 */
	public Textsize createTextsize()
	{
		return new Textsize();
	}

	/**
	 * Create an instance of {@link Bitmap }
	 * 
	 */
	public Bitmap createBitmap()
	{
		return new Bitmap();
	}

	/**
	 * Create an instance of {@link Pen }
	 * 
	 */
	public Pen createPen()
	{
		return new Pen();
	}

	/**
	 * Create an instance of {@link Info }
	 * 
	 */
	public Info createInfo()
	{
		return new Info();
	}

	/**
	 * Create an instance of {@link Ipe }
	 * 
	 */
	public Ipe createIpe()
	{
		return new Ipe();
	}

	/**
	 * Create an instance of {@link Ipestyle }
	 * 
	 */
	public Ipestyle createIpestyle()
	{
		return new Ipestyle();
	}

	/**
	 * Create an instance of {@link Page }
	 * 
	 */
	public Page createPage()
	{
		return new Page();
	}

	/**
	 * Create an instance of {@link Dashstyle }
	 * 
	 */
	public Dashstyle createDashstyle()
	{
		return new Dashstyle();
	}

	/**
	 * Create an instance of {@link Textstyle }
	 * 
	 */
	public Textstyle createTextstyle()
	{
		return new Textstyle();
	}

	/**
	 * Create an instance of {@link Gradient }
	 * 
	 */
	public Gradient createGradient()
	{
		return new Gradient();
	}

	/**
	 * Create an instance of {@link Stop }
	 * 
	 */
	public Stop createStop()
	{
		return new Stop();
	}

	/**
	 * Create an instance of {@link Cmap }
	 * 
	 */
	public Cmap createCmap()
	{
		return new Cmap();
	}

	/**
	 * Create an instance of {@link Layout }
	 * 
	 */
	public Layout createLayout()
	{
		return new Layout();
	}

	/**
	 * Create an instance of {@link Textpad }
	 * 
	 */
	public Textpad createTextpad()
	{
		return new Textpad();
	}

	/**
	 * Create an instance of {@link Titlestyle }
	 * 
	 */
	public Titlestyle createTitlestyle()
	{
		return new Titlestyle();
	}

	/**
	 * Create an instance of {@link Pagenumberstyle }
	 * 
	 */
	public Pagenumberstyle createPagenumberstyle()
	{
		return new Pagenumberstyle();
	}

	/**
	 * Create an instance of {@link Pathstyle }
	 * 
	 */
	public Pathstyle createPathstyle()
	{
		return new Pathstyle();
	}

	/**
	 * Create an instance of {@link Effect }
	 * 
	 */
	public Effect createEffect()
	{
		return new Effect();
	}

	/**
	 * Create an instance of {@link Textstretch }
	 * 
	 */
	public Textstretch createTextstretch()
	{
		return new Textstretch();
	}

	/**
	 * Create an instance of {@link Opacity }
	 * 
	 */
	public Opacity createOpacity()
	{
		return new Opacity();
	}

	/**
	 * Create an instance of {@link Symbolsize }
	 * 
	 */
	public Symbolsize createSymbolsize()
	{
		return new Symbolsize();
	}

	/**
	 * Create an instance of {@link Arrowsize }
	 * 
	 */
	public Arrowsize createArrowsize()
	{
		return new Arrowsize();
	}

	/**
	 * Create an instance of {@link Anglesize }
	 * 
	 */
	public Anglesize createAnglesize()
	{
		return new Anglesize();
	}

}
