//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "value" })
@XmlRootElement(name = "pagenumberstyle")
public class Pagenumberstyle
{

	@XmlAttribute(name = "pos", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pos;
	@XmlAttribute(name = "color")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String color;
	@XmlAttribute(name = "size")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String size;
	@XmlAttribute(name = "valign")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String valign;
	@XmlAttribute(name = "halign")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String halign;
	@XmlValue
	protected String value;

	/**
	 * Gets the value of the pos property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPos()
	{
		return pos;
	}

	/**
	 * Sets the value of the pos property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPos(String value)
	{
		this.pos = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor()
	{
		if (color == null) {
			return "black";
		} else {
			return color;
		}
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(String value)
	{
		this.color = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSize()
	{
		if (size == null) {
			return "normal";
		} else {
			return size;
		}
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSize(String value)
	{
		this.size = value;
	}

	/**
	 * Gets the value of the valign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValign()
	{
		if (valign == null) {
			return "baseline";
		} else {
			return valign;
		}
	}

	/**
	 * Sets the value of the valign property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValign(String value)
	{
		this.valign = value;
	}

	/**
	 * Gets the value of the halign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHalign()
	{
		if (halign == null) {
			return "left";
		} else {
			return halign;
		}
	}

	/**
	 * Sets the value of the halign property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHalign(String value)
	{
		this.halign = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getvalue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setvalue(String value)
	{
		this.value = value;
	}

}
