//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "value" })
@XmlRootElement(name = "path")
public class Path
{

	@XmlAttribute(name = "layer")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String layer;
	@XmlAttribute(name = "matrix")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String matrix;
	@XmlAttribute(name = "pin")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String pin;
	@XmlAttribute(name = "transformations")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String transformations;
	@XmlAttribute(name = "stroke")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String stroke;
	@XmlAttribute(name = "fill")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String fill;
	@XmlAttribute(name = "tiling")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String tiling;
	@XmlAttribute(name = "gradient")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String gradient;
	@XmlAttribute(name = "dash")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String dash;
	@XmlAttribute(name = "pen")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pen;
	@XmlAttribute(name = "opacity")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String opacity;
	@XmlAttribute(name = "cap")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String cap;
	@XmlAttribute(name = "join")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String join;
	@XmlAttribute(name = "fillrule")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String fillrule;
	@XmlAttribute(name = "arrow")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String arrow;
	@XmlAttribute(name = "rarrow")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String rarrow;
	@XmlValue
	protected String value;

	/**
	 * Gets the value of the layer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLayer()
	{
		return layer;
	}

	/**
	 * Sets the value of the layer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLayer(String value)
	{
		this.layer = value;
	}

	/**
	 * Gets the value of the matrix property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMatrix()
	{
		if (matrix == null) {
			return "1 0 0 1 0 0";
		} else {
			return matrix;
		}
	}

	/**
	 * Sets the value of the matrix property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMatrix(String value)
	{
		this.matrix = value;
	}

	/**
	 * Gets the value of the pin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPin()
	{
		return pin;
	}

	/**
	 * Sets the value of the pin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPin(String value)
	{
		this.pin = value;
	}

	/**
	 * Gets the value of the transformations property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransformations()
	{
		if (transformations == null) {
			return "affine";
		} else {
			return transformations;
		}
	}

	/**
	 * Sets the value of the transformations property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransformations(String value)
	{
		this.transformations = value;
	}

	/**
	 * Gets the value of the stroke property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStroke()
	{
		return stroke;
	}

	/**
	 * Sets the value of the stroke property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStroke(String value)
	{
		this.stroke = value;
	}

	/**
	 * Gets the value of the fill property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFill()
	{
		return fill;
	}

	/**
	 * Sets the value of the fill property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFill(String value)
	{
		this.fill = value;
	}

	/**
	 * Gets the value of the tiling property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTiling()
	{
		if (tiling == null) {
			return "normal";
		} else {
			return tiling;
		}
	}

	/**
	 * Sets the value of the tiling property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTiling(String value)
	{
		this.tiling = value;
	}

	/**
	 * Gets the value of the gradient property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGradient()
	{
		if (gradient == null) {
			return "normal";
		} else {
			return gradient;
		}
	}

	/**
	 * Sets the value of the gradient property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGradient(String value)
	{
		this.gradient = value;
	}

	/**
	 * Gets the value of the dash property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDash()
	{
		return dash;
	}

	/**
	 * Sets the value of the dash property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDash(String value)
	{
		this.dash = value;
	}

	/**
	 * Gets the value of the pen property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPen()
	{
		if (pen == null) {
			return "normal";
		} else {
			return pen;
		}
	}

	/**
	 * Sets the value of the pen property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPen(String value)
	{
		this.pen = value;
	}

	/**
	 * Gets the value of the opacity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOpacity()
	{
		if (opacity == null) {
			return "normal";
		} else {
			return opacity;
		}
	}

	/**
	 * Sets the value of the opacity property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOpacity(String value)
	{
		this.opacity = value;
	}

	/**
	 * Gets the value of the cap property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCap()
	{
		return cap;
	}

	/**
	 * Sets the value of the cap property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCap(String value)
	{
		this.cap = value;
	}

	/**
	 * Gets the value of the join property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getJoin()
	{
		return join;
	}

	/**
	 * Sets the value of the join property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setJoin(String value)
	{
		this.join = value;
	}

	/**
	 * Gets the value of the fillrule property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFillrule()
	{
		return fillrule;
	}

	/**
	 * Sets the value of the fillrule property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFillrule(String value)
	{
		this.fillrule = value;
	}

	/**
	 * Gets the value of the arrow property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArrow()
	{
		return arrow;
	}

	/**
	 * Sets the value of the arrow property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArrow(String value)
	{
		this.arrow = value;
	}

	/**
	 * Gets the value of the rarrow property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRarrow()
	{
		return rarrow;
	}

	/**
	 * Sets the value of the rarrow property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRarrow(String value)
	{
		this.rarrow = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getvalue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setvalue(String value)
	{
		this.value = value;
	}

}
