//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "groupOrImageOrUseOrTextOrPath" })
@XmlRootElement(name = "symbol")
public class Symbol
{

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "xform")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String xform;
	@XmlAttribute(name = "transformations")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String transformations;
	@XmlElements({
			@XmlElement(name = "group", required = true, type = Group.class),
			@XmlElement(name = "image", required = true, type = Image.class),
			@XmlElement(name = "use", required = true, type = Use.class),
			@XmlElement(name = "text", required = true, type = Text.class),
			@XmlElement(name = "path", required = true, type = Path.class) })
	protected List<Object> groupOrImageOrUseOrTextOrPath;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the xform property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getXform()
	{
		if (xform == null) {
			return "no";
		} else {
			return xform;
		}
	}

	/**
	 * Sets the value of the xform property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setXform(String value)
	{
		this.xform = value;
	}

	/**
	 * Gets the value of the transformations property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransformations()
	{
		return transformations;
	}

	/**
	 * Sets the value of the transformations property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransformations(String value)
	{
		this.transformations = value;
	}

	/**
	 * Gets the value of the groupOrImageOrUseOrTextOrPath property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the groupOrImageOrUseOrTextOrPath property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getGroupOrImageOrUseOrTextOrPath().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Group }
	 * {@link Image } {@link Use } {@link Text } {@link Path }
	 * 
	 * 
	 */
	public List<Object> getGroupOrImageOrUseOrTextOrPath()
	{
		if (groupOrImageOrUseOrTextOrPath == null) {
			groupOrImageOrUseOrTextOrPath = new ArrayList<Object>();
		}
		return this.groupOrImageOrUseOrTextOrPath;
	}

}
