//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "textpad")
public class Textpad
{

	@XmlAttribute(name = "left", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String left;
	@XmlAttribute(name = "right", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String right;
	@XmlAttribute(name = "top", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String top;
	@XmlAttribute(name = "bottom", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String bottom;

	/**
	 * Gets the value of the left property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLeft()
	{
		return left;
	}

	/**
	 * Sets the value of the left property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLeft(String value)
	{
		this.left = value;
	}

	/**
	 * Gets the value of the right property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRight()
	{
		return right;
	}

	/**
	 * Sets the value of the right property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRight(String value)
	{
		this.right = value;
	}

	/**
	 * Gets the value of the top property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTop()
	{
		return top;
	}

	/**
	 * Sets the value of the top property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTop(String value)
	{
		this.top = value;
	}

	/**
	 * Gets the value of the bottom property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBottom()
	{
		return bottom;
	}

	/**
	 * Sets the value of the bottom property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBottom(String value)
	{
		this.bottom = value;
	}

}
