//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "value" })
@XmlRootElement(name = "text")
public class Text
{

	@XmlAttribute(name = "layer")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String layer;
	@XmlAttribute(name = "matrix")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String matrix;
	@XmlAttribute(name = "pin")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String pin;
	@XmlAttribute(name = "transformations")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String transformations;
	@XmlAttribute(name = "type")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String type;
	@XmlAttribute(name = "stroke")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String stroke;
	@XmlAttribute(name = "size")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String size;
	@XmlAttribute(name = "pos", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pos;
	@XmlAttribute(name = "width")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String width;
	@XmlAttribute(name = "opacity")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String opacity;
	@XmlAttribute(name = "height")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String height;
	@XmlAttribute(name = "depth")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String depth;
	@XmlAttribute(name = "valign")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String valign;
	@XmlAttribute(name = "halign")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String halign;
	@XmlAttribute(name = "style")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String style;
	@XmlValue
	protected String value;

	/**
	 * Gets the value of the layer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLayer()
	{
		return layer;
	}

	/**
	 * Sets the value of the layer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLayer(String value)
	{
		this.layer = value;
	}

	/**
	 * Gets the value of the matrix property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMatrix()
	{
		if (matrix == null) {
			return "1 0 0 1 0 0";
		} else {
			return matrix;
		}
	}

	/**
	 * Sets the value of the matrix property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMatrix(String value)
	{
		this.matrix = value;
	}

	/**
	 * Gets the value of the pin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPin()
	{
		return pin;
	}

	/**
	 * Sets the value of the pin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPin(String value)
	{
		this.pin = value;
	}

	/**
	 * Gets the value of the transformations property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransformations()
	{
		if (transformations == null) {
			return "affine";
		} else {
			return transformations;
		}
	}

	/**
	 * Sets the value of the transformations property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransformations(String value)
	{
		this.transformations = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType()
	{
		if (type == null) {
			return "label";
		} else {
			return type;
		}
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value)
	{
		this.type = value;
	}

	/**
	 * Gets the value of the stroke property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStroke()
	{
		if (stroke == null) {
			return "black";
		} else {
			return stroke;
		}
	}

	/**
	 * Sets the value of the stroke property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStroke(String value)
	{
		this.stroke = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSize()
	{
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSize(String value)
	{
		this.size = value;
	}

	/**
	 * Gets the value of the pos property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPos()
	{
		return pos;
	}

	/**
	 * Sets the value of the pos property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPos(String value)
	{
		this.pos = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWidth(String value)
	{
		this.width = value;
	}

	/**
	 * Gets the value of the opacity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOpacity()
	{
		if (opacity == null) {
			return "normal";
		} else {
			return opacity;
		}
	}

	/**
	 * Sets the value of the opacity property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOpacity(String value)
	{
		this.opacity = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeight(String value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the depth property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDepth()
	{
		return depth;
	}

	/**
	 * Sets the value of the depth property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepth(String value)
	{
		this.depth = value;
	}

	/**
	 * Gets the value of the valign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValign()
	{
		return valign;
	}

	/**
	 * Sets the value of the valign property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValign(String value)
	{
		this.valign = value;
	}

	/**
	 * Gets the value of the halign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHalign()
	{
		return halign;
	}

	/**
	 * Sets the value of the halign property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHalign(String value)
	{
		this.halign = value;
	}

	/**
	 * Gets the value of the style property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStyle()
	{
		return style;
	}

	/**
	 * Sets the value of the style property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStyle(String value)
	{
		this.style = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getvalue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setvalue(String value)
	{
		this.value = value;
	}

}
