//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "tiling")
public class Tiling
{

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "angle", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String angle;
	@XmlAttribute(name = "step", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String step;
	@XmlAttribute(name = "width", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String width;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the angle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAngle()
	{
		return angle;
	}

	/**
	 * Sets the value of the angle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAngle(String value)
	{
		this.angle = value;
	}

	/**
	 * Gets the value of the step property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStep()
	{
		return step;
	}

	/**
	 * Sets the value of the step property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStep(String value)
	{
		this.step = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWidth(String value)
	{
		this.width = value;
	}

}
