//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "titlestyle")
public class Titlestyle
{

	@XmlAttribute(name = "pos", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pos;
	@XmlAttribute(name = "color", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String color;
	@XmlAttribute(name = "size", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String size;
	@XmlAttribute(name = "halign")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String halign;
	@XmlAttribute(name = "valign")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String valign;

	/**
	 * Gets the value of the pos property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPos()
	{
		return pos;
	}

	/**
	 * Sets the value of the pos property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPos(String value)
	{
		this.pos = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor()
	{
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(String value)
	{
		this.color = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSize()
	{
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSize(String value)
	{
		this.size = value;
	}

	/**
	 * Gets the value of the halign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHalign()
	{
		return halign;
	}

	/**
	 * Sets the value of the halign property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHalign(String value)
	{
		this.halign = value;
	}

	/**
	 * Gets the value of the valign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValign()
	{
		return valign;
	}

	/**
	 * Sets the value of the valign property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValign(String value)
	{
		this.valign = value;
	}

}
