//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "use")
public class Use
{

	@XmlAttribute(name = "layer")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String layer;
	@XmlAttribute(name = "matrix")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String matrix;
	@XmlAttribute(name = "pin")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String pin;
	@XmlAttribute(name = "transformations")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String transformations;
	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "size")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String size;
	@XmlAttribute(name = "pos")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pos;
	@XmlAttribute(name = "stroke")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String stroke;
	@XmlAttribute(name = "fill")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String fill;
	@XmlAttribute(name = "pen")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String pen;

	/**
	 * Gets the value of the layer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLayer()
	{
		return layer;
	}

	/**
	 * Sets the value of the layer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLayer(String value)
	{
		this.layer = value;
	}

	/**
	 * Gets the value of the matrix property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMatrix()
	{
		if (matrix == null) {
			return "1 0 0 1 0 0";
		} else {
			return matrix;
		}
	}

	/**
	 * Sets the value of the matrix property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMatrix(String value)
	{
		this.matrix = value;
	}

	/**
	 * Gets the value of the pin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPin()
	{
		return pin;
	}

	/**
	 * Sets the value of the pin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPin(String value)
	{
		this.pin = value;
	}

	/**
	 * Gets the value of the transformations property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransformations()
	{
		if (transformations == null) {
			return "affine";
		} else {
			return transformations;
		}
	}

	/**
	 * Sets the value of the transformations property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransformations(String value)
	{
		this.transformations = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSize()
	{
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSize(String value)
	{
		this.size = value;
	}

	/**
	 * Gets the value of the pos property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPos()
	{
		return pos;
	}

	/**
	 * Sets the value of the pos property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPos(String value)
	{
		this.pos = value;
	}

	/**
	 * Gets the value of the stroke property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStroke()
	{
		if (stroke == null) {
			return "black";
		} else {
			return stroke;
		}
	}

	/**
	 * Sets the value of the stroke property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStroke(String value)
	{
		this.stroke = value;
	}

	/**
	 * Gets the value of the fill property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFill()
	{
		if (fill == null) {
			return "black";
		} else {
			return fill;
		}
	}

	/**
	 * Sets the value of the fill property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFill(String value)
	{
		this.fill = value;
	}

	/**
	 * Gets the value of the pen property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPen()
	{
		if (pen == null) {
			return "normal";
		} else {
			return pen;
		}
	}

	/**
	 * Sets the value of the pen property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPen(String value)
	{
		this.pen = value;
	}

}
