//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 11:24:44 AM CEST 
//

package de.topobyte.ipe.jaxb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "view")
public class View
{

	@XmlAttribute(name = "layers", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String layers;
	@XmlAttribute(name = "active", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String active;
	@XmlAttribute(name = "effect")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String effect;
	@XmlAttribute(name = "marked")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String marked;

	/**
	 * Gets the value of the layers property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLayers()
	{
		return layers;
	}

	/**
	 * Sets the value of the layers property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLayers(String value)
	{
		this.layers = value;
	}

	/**
	 * Gets the value of the active property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getActive()
	{
		return active;
	}

	/**
	 * Sets the value of the active property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setActive(String value)
	{
		this.active = value;
	}

	/**
	 * Gets the value of the effect property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEffect()
	{
		if (effect == null) {
			return "normal";
		} else {
			return effect;
		}
	}

	/**
	 * Sets the value of the effect property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEffect(String value)
	{
		this.effect = value;
	}

	/**
	 * Gets the value of the marked property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMarked()
	{
		if (marked == null) {
			return "yes";
		} else {
			return marked;
		}
	}

	/**
	 * Sets the value of the marked property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMarked(String value)
	{
		this.marked = value;
	}

}
